### ISSUE TITLE
Publish Build Artifacts task is being skipped (Also having failed build)

### ISSUE THREAD

**Issue by Yecats** [Dinomite-Studios/unity-azure-pipelines-tasks#104]
My build is failing and I'm trying to troubleshoot why by accessing the editor log. My problem is that I cannot access the log because the Publish Build Artifacts task is being skipped. I've tried researching what causes the skip to happen and have come up empty handed. 

Here's the definition that I have:

```yaml

- task: UnityBuildTask@3
  name: unitybuild
  displayName: 'Build Project'
  inputs:
    buildTarget: 'standalone'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'drop'
    additionalCmdArgs: '-logFile $(Build.ArtifactStagingDirectory)\build_logs\EditorLog.log'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(unitybuild.buildOutputPath)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

```

![image](https://user-images.githubusercontent.com/4108756/64913703-b433b880-d6f9-11e9-8558-b64dbca9eb02.png)
