### ISSUE TITLE
UnityTestTask 1.4.2 stalls indefinitely

### ISSUE THREAD

**Issue by fnuecke** [Dinomite-Studios/unity-azure-pipelines-tasks#174]
`UnityTestTask@1.4.2` stalls our pipeline indefinitely. The Unity log reaches the end, but the task never appears to detect that Unity quit. With diagnostics logging enabled, it is logged that Unity quits with exit code 0. Looking at the taks manager on the build machine, node appears to still be running unitl the job is canceled. Pinning the test tasks to 1.4.0 works and allows the pipeline to finish.

This happens for both Unity 2019.3.6f1 and Unity 2020.3.3f1.

I'm afraid I cannot say why exactly this is. It seems suspicious that the return code check changed, but looking at the diff it looks like it should not make a difference to me. Then again, I'm not very versed in TypeScript, so there may be a subtle difference in semantics I'm not seeing.

I have not tested whether this behaves differently (as in, does not stall) in case any tests fail. If this would be helpful information, let me know and I'll look into it.

**Comment by ikriz** [comment]
#136  think this is related :)

**Comment by fnuecke** [comment]
Oh, that definitely sounds related! Sorry, I missed that issue.

Here's the relevant task from our pipeline .yml:
```yml
  - task: UnityTestTask@1.4.0
    displayName: 'Editor Tests Development'
    inputs:
      unityEditorsPathMode: 'specify'
      customUnityEditorsPath: 'C:\Program Files\Unity\'
      unityProjectPath: 'Development'
      testResultsPath: 'TestResults'
      testCategory: 'CPU'
```

The `@1.4.0` being what we use to work around the issue for now. Previously was just `@1`, so latest, so `1.4.2`.
