### ISSUE TITLE
UnityCMD results in an error when run as a Task - "path" argument must be of type string

### ISSUE THREAD

**Issue by SimonDarksideJ** [Dinomite-Studios/unity-azure-pipelines-tasks#223]
When running the following UnityCMD task in an attempt to try and activate a personal license, the Log simply spit out the following error:

```text
==============================================================================
The "path" argument must be of type string. Received type undefined
##[error]The "path" argument must be of type string. Received type undefined
```

YAML

```yaml
- task: UnityCMDTask@1
  name: UnityLogin
  inputs:
    unityProjectPath: 'TheMostAwesomeGameEverMade/'
    cmdArgs: '-quit -nographics -username $(unity.username) -password $(unity.password)'
```

The help for the Task indicates that:

```text
Specify command line arguments. The task will set -batchmode, -projectPath, -buildTarget and -logfile for you. See the [documentation](https://docs.unity3d.com/Manual/CommandLineArguments.html) for more info.
```

So no path was expected to be added?
