### ISSUE TITLE
Unity Activate License's post-job should not run if task was skipped

### ISSUE THREAD

**Issue by derekfreed** [Dinomite-Studios/unity-azure-pipelines-tasks#241]
I have a pipeline where we may either license using a unity licensing server or license with a serial with UnityActivateLicense Task.

In the case where we license with the Unity License Server, we skip the UnityActivateLicense task, but I'm seeing that the post-job that is meant to release the license from UnityActivateLicense still runs even if the task was skipped due to a yaml condition.

My expectation is that the post-job should not run if the UnityActivateLicense task does not run.

![image](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/assets/10147303/0fb91cbc-56c8-47e1-89eb-23ca137009a0)

**Comment by derekfreed** [comment]
One workaround for this that I've found is using conditional insertion like so:

```yaml
  - ${{ if eq(variables.Unity_LicenseWithServer, false) }}:
    - task: UnityActivateLicenseTask@1
      name: unityactivation
      inputs:
        username: $(unityusername)
        password: $(unitypassword)
        serial: $(unityserial)
```
where Unity_LicenseWithServer is defined as a variable at the job level (I set that variable using a parameter that defaults to a value coming from a variable template)
