### ISSUE TITLE
Last version crash on azure

### ISSUE THREAD

**Issue by odlex** [Dinomite-Studios/unity-azure-pipelines-tasks#261]
Hi,

All our projects now fail during build since two hour ago! 

Your last version 1.2.1 won't work.

crash log:
```
Starting: unitycmd
==============================================================================
Task         : Unity CMD
Description  : Execute a Unity editor via command line.
Version      : 1.2.1
Author       : Dinomite
Help         : Use this task for full control over the arguments passed to the Untiy command line. With this task you are free to implement any custom behaviour needed. [More Information](https://unitydevops.com/docs/unity-cmd-task).
==============================================================================
Invalid path mode for editors folder lookup specified.
##[error]Invalid path mode for editors folder lookup specified.
Finishing: unitycmd

```
**extract of original azure-pipeline.yml**:
```
...
      - task: UnityCMDTask@1
        name: unitycmd
        inputs:
          unityEditorsPathMode: unityHub
          cmdArgs: -buildTarget win64 .....
....
```
****
if we force on - task: UnityCMDTask@1.2.0, it's work.
