### ISSUE TITLE
Using buildScriptType: existing adds -quit argument automatically. Quitting early in cases which use EditorApplication.Exit(0);

### ISSUE THREAD

**Issue by Wully616** [Dinomite-Studios/unity-azure-pipelines-tasks#290]
# Unity Tools for Azure DevOps - Bug Report

## Describe the bug

Using UnityBuildTask@3 with `buildScriptType: existing` appends `-quit` to the command line arguments.

This causes executed script methods which start coroutines to not wait on the coroutines and immedietly quit, causing the task to fail.

If we want to add -quit it should be done via the `additionalCmdArgs`

## To Reproduce
Have a method which starts a coroutine, which will exit the app on its own once its complete

```cs
file: Example.cs

        public static void PipelineBuildMethod()
        {
            EditorCoroutineUtility.StartCoroutineOwnerless(CoroutineThatQuitsApp());
        }

        static IEnumerator CoroutineThatQuitsApp()
        {
            yield return new WaitForSeconds(10);
            EditorApplication.Exit(0);
        }
```        

Have the build task use `buildScriptType: existing` and point to the method which starts the coroutine
```
    - task: UnityBuildTask@3      
      displayName: 'Baking'
      inputs:
        buildTarget: standalone
        unityProjectPath: '$(Agent.WorkFolder)\$(unityFolderName)'
        buildScriptType: existing
        scriptExecuteMethod: Example.PipelineBuildMethod
        additionalCmdArgs: ''
```
## Expected behavior

The example should run for 10 seconds then quit
Expected command generated:
```
"C:\Program Files\Unity\Hub\Editor\2021.3.38f1\Editor\Unity.exe"
 -batchmode 
 -buildTarget standalone 
 -projectPath <REMOVED>
 -logfile <REMOVED>
 -executeMethod Example.PipelineBuildMethod
```

## Actual behavior
-quit is appended to the command line arguments, so after the coroutine is started, the application will immediately quit instead of executing the coroutine fully

Generated command line:
```
"C:\Program Files\Unity\Hub\Editor\2021.3.38f1\Editor\Unity.exe"
 -batchmode 
 -buildTarget standalone 
 -projectPath <REMOVED>
 -logfile <REMOVED>
 -executeMethod Example.PipelineBuildMethod
 -quit
```

## Screenshots

it looks like this part of the code adding it

![image](https://github.com/user-attachments/assets/197ba17a-87c3-4f18-baf6-cb0eae0555b8)

### Agent Type

- [ ] Hosted
- [X] Self Hosted

### Build Targets

- [X] Windows
- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Other (please specifiy)

### Unity Version

2021.3.38f1
